name: Test

on:
  push:
    branches: [ master ]
    paths: 
      - "test.py"
      - "a2clib.py"
  pull_request:
    branches: [ master ]
    paths: 
      - "test.py"
      - "a2clib.py"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test the app
      run: |
        python test.py
